"""empty message

Revision ID: 45d24bfed1c0
Revises: 16e5de501d60
Create Date: 2021-03-15 16:19:32.074818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d24bfed1c0'
down_revision = '16e5de501d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###
