"""empty message

Revision ID: 51d1150b7a2c
Revises: 45d24bfed1c0
Create Date: 2021-03-15 17:43:49.896409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d1150b7a2c'
down_revision = '45d24bfed1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    op.drop_table('cursos')
    op.drop_table('instituicoes')
    # ### end Alembic commands ###
